### ISSUE TITLE
Mi arrendo!

### ISSUE THREAD

**Issue by RuggieroB** [RuggieroB/socket#1]
@FabioZTessitore  Gentile Professore;
Mi arrendo ufficialmente sulla risoluzione di questo esercizio (esercizio2 - comunicazione fin quando il client non decide di terminarla)!
AIUTO!

**Comment by FabioZTessitore** [comment]
appena possibile pubblico la soluzione

**Comment by RuggieroB** [comment]
Addirittura! No, grazie: voglio capire dove ho sbagliato e come correggere.
Ci riprovo e l’aggiorno.
Grazie 



Inviato da Libero Mail per iOS


giovedì 31 ottobre 2019, 08:02 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by RuggieroB** [comment]
Buondì;
Come mai ha chiuso l’issue nonostante ancora non avessi corretto?



Inviato da Libero Mail per iOS


venerdì 28 febbraio 2020, 12:50 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
pensavo fosse argomento superato

**Comment by RuggieroB** [comment]
Comprendo.
Devo però riuscire a risolverlo!
Buon venerdì 



Inviato da Libero Mail per iOS


venerdì 28 febbraio 2020, 13:42 +0100 da notifications@github.com  <notifications@github.com>:
